import Head from "next/head";
import Card from "@/components/Card";
import Link from "next/link";

export async function getServerSideProps() {
  try {
    const res = await fetch(`https://jsonplaceholder.typicode.com/users/`);
    const data = await res.json();
    return { props: { data } };
  } catch (error) {
    console.error(error);
    throw new Error('failed to fetch data')
  }
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Dynamic Meta Image</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 p-4 sm:grid sm:grid-cols-2 md:grid-cols-3">
        {data.map((card, index) => (
          <Link key={card.id} href={`users/${card.id}`}>
            <Card {...card} />
          </Link>
        ))}
      </main>
    </>
  );
}
