import Head from "next/head";
import Card from "@/components/Card";

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:4000/data`);
  const data = await res.json();
  console.log(data);

  return { props: { data } };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-4 p-4 sm:grid sm:grid-cols-2 md:grid-cols-3">
        {data.map((data) => (
          <Card key={data.id} {...data} />
        ))}
      </main>
    </>
  );
}
